- .gitignore
- sass/base/_components.scss
- sass/base/_core.scss
- sass/base/_variables.scss
https://comicrelief.atlassian.net/browse/PL-10
> fix: dont ignore globbing sass files

- sass/base/_components.scss
https://comicrelief.atlassian.net/browse/PL-14
> fix: update components globbing file

- sass/themes/cr/2017/variables/_colours.scss
> fix: cr index

- sass/themes/cr/2017/cr17.scss
> fix: add news to cr theme

- sass/themes/cr/2017/components/single-msg/_single-msg.scss
- sass/themes/cr/2017/components/single-msg/single-msg.twig
> fix: update no bg colour single message

- sass/base/components/footer/footer.twig
- sass/base/variables/_colours.scss
- sass/themes/cr/2017/_cr17-components.scss
- sass/themes/cr/2017/components/background-colours/_background-colours.scss
- sass/themes/cr/2017/components/background-colours/background-colours.twig
- sass/themes/cr/2017/cr17.scss
- sass/themes/cr/2017/variables/_colours.scss
updating bg colours for cr theme
> fix: cr update colours

- sass/base/_components.scss
- sass/base/components/feature-articles-block/_feature-articles-block.scss
- sass/base/components/feature-articles-block/feature-articles-block.twig
> feat: new feature articles block component

- sass/themes/frost/components/_modal.scss
- sass/themes/frost/frost.scss
Form overlay extend to the end of the page, not just covering the expected field,
so overlays intersect and extend beyond page end
> GP 257 form overlay

- sass/base/components/feature-articles-block/_feature-articles-block.scss
- sass/base/components/feature-articles-block/feature-articles-block.twig
> fix: fix feature article paragraph layout

- sass/base/components/feature-articles-block/_feature-articles-block.scss
- sass/base/components/feature-articles-block/feature-articles-block.twig
Small change on Paragraph Article category layout
> fix: change article paragraph layout

- sass/themes/cr/2017/components/single-msg/_single-msg.scss
> fix: layout options negative remove margins

- sass/base/components/search/_search-block.scss
> fix: search block clearfix form max-width

- sass/base/components/cookie-consent/_cookie-consent.scss
- sass/base/components/email-signup/_email-signup.scss
- sass/base/components/email-signup/email-signup-workplace.twig
- sass/base/components/typography/_typography.scss
- sass/base/components/typography/typography.twig
- sass/themes/cr/2017/_cr17-components.scss
- sass/themes/cr/2017/components/buttons/_buttons.scss
- sass/themes/cr/2017/components/buttons/buttons.twig
- sass/themes/cr/2017/components/links/_links.scss
- sass/themes/cr/2017/components/links/links.twig
- sass/themes/cr/2017/components/typography/_typography.scss
- sass/themes/cr/2017/components/typography/typography.twig
- sass/themes/cr/2017/cr17.scss
> fix: update cr theme overrides

- sass/themes/frost/components/_progress_indicator.scss
> fix: replace flex display for progress indicator #85

- sass/base/components/email-signup/_email-signup.scss
> fix: esu tablet input fix

- sass/themes/cr/2017/_cr17-components.scss
- sass/themes/cr/2017/components/buttons/_buttons.scss
- sass/themes/cr/2017/components/highlight/_highlight.scss
- sass/themes/cr/2017/components/highlight/highlight.twig
- sass/themes/cr/2017/components/links/links.twig
- sass/themes/cr/2017/variables/_colours.scss
> fix: add highlight update bg colours

- sass/base/core/_base-1-mixins.scss
> fix: clearfix update

- sass/base/components/social/_social.scss
> fix: update transform fix

- sass/base/components/email-signup/_email-signup-head.scss
- sass/base/components/footer/_footer.scss
- sass/base/components/search/_search-block.scss
> fix: esu search check footer

- Gruntfile.js
> #110: removed unnecessary npm code

- Gruntfile.js
- sass/base/_components.scss
- sass/base/components/form/_form.scss
- sass/base/components/progress-indicator/_progress-indicator.scss
- sass/base/components/progress-indicator/progress-indicator.twig
- sass/kss/frost.scss
- sass/themes/frost/components/_cookie-consent.scss
- sass/themes/frost/components/_footer.scss
- sass/themes/frost/components/_form.scss
- sass/themes/frost/components/footer-nav.twig
- sass/themes/frost/frost.scss
- sass/themes/frost/homepage.md
- sass/themes/frost/variables/_typography.scss
- sass/themes/frost/variables/typography.twig
- move progress indicator to core
- fixes #108
> feat: Frost styleguide structure update

- sass/base/components/form/_form.scss
- sass/themes/frost/components/_form.scss
> fix: Frost update nav button full width

- sass/base/core/_base-fonts.scss
- sass/themes/cr/2017/_cr17-components.scss
- sass/themes/cr/2017/components/buttons/_buttons.scss
- sass/themes/cr/2017/components/buttons/buttons.twig
- sass/themes/cr/2017/components/highlight/_highlight.scss
- sass/themes/cr/2017/components/links/_links.scss
- sass/themes/cr/2017/components/links/links.twig
- sass/themes/cr/2017/components/typography/_fonts.scss
- sass/themes/cr/2017/components/typography/_typography.scss
- sass/themes/cr/2017/components/typography/typography.twig
- sass/themes/cr/2017/cr17.scss
- sass/themes/cr/2017/variables/_colours.scss
- sass/themes/cr/2017/variables/_mixins.scss
- sass/themes/cr/2017/variables/_typography.scss
- sass/themes/cr/2017/variables/colour.twig
> 106 update links btn font colour cr theme

- sass/base/components/promo-header/_promo-header.scss
> fix: promo header mobile img copy over

- sass/base/core/_base-fonts.scss
Get fonts over https to avoid security warnings
GP-311
> fix: Fonts warnings

- README.md
> Add concourse badge in README and remove (useless) Travis badge

- sass/base/components/media-block/_media-block.scss
- sass/base/components/media-block/media-block.twig
- sass/themes/cr/2017/_cr17-components.scss
- sass/themes/cr/2017/components/media-block/_media-block.scss
- sass/themes/cr/2017/components/media-block/media-block.twig
> fix: block ref colour

- sass/themes/cr/2017/_cr17-components.scss
- sass/themes/cr/2017/components/loading/_loading.scss
> feat: add cr loading animation

- sass/base/_components.scss
- sass/themes/cr/2017/components/highlight/_highlight.scss
- sass/themes/cr/2017/components/media-block/_media-block.scss
> fix: hightlight class and media ref colour

- sass/themes/cr/2017/components/typography/_typography.scss
- sass/themes/cr/2017/variables/_typography.scss
> fix: update cr typo

- sass/base/components/news-article/news-article.twig
- sass/themes/cr/2017/components/links/_links.scss
> fix: add default link style

- sass/base/components/header/_base-header.scss
- sass/base/components/navigation/_main-nav.scss
> fix: navigation breakpoint

- sass/base/components/email-signup/_email-signup-head.scss
> Fix ESU header 

- sass/themes/cr/2017/components/navigation/_main-nav.scss
Forgot to update version number in the previous PR, whoops.
> Style tidy-up, trigger new release for CR nav styles

- sass/themes/cr/2017/components/navigation/_main-nav.scss
> Tweaking item padding to fit container properly

- sass/base/components/email-signup/_email-signup-head.scss
- sass/base/components/header/_base-header.scss
- sass/base/components/navigation/_main-nav.scss
- sass/themes/cr/2017/components/navigation/_main-nav.scss
> Nav bug fix IE

- sass/themes/cr/2017/components/navigation/_main-nav.scss
> Fix: Desktop nav item padding

- sass/base/components/content-wall/_content-wall.scss
- sass/base/components/views/_views.scss
> fix: overlay padding mobile and style duplication

- sass/base/components/search/_search-block.scss
> Search block IE fix

- package.json
> fix: add version to package json

- package.json
> fix: version package desc msg

- sass/themes/cr/2017/components/navigation/_main-nav.scss
> Meta-icon heights

- sass/themes/cr/2017/components/navigation/_main-nav.scss
> Banner height tweak to fit metaicons properly

- sass/themes/cr/2017/variables/_mixins.scss
> fix: inline link font inherit

- sass/base/core/_base-reset.scss
> Add font smoothing to base theme

- sass/base/_components.scss
- sass/base/components/table/_table.scss
- sass/base/components/table/table.twig
- sass/themes/cr/2017/cr17.scss
> feat: Add table component

- sass/themes/frost/components/_form.scss
change class names related to email submit button styling
> fix: Frost reg. email step

- sass/themes/cr/2017/components/single-msg/_single-msg.scss
> 243 - fix padding same height

- sass/base/components/email-signup/_email-signup-head.scss
- sass/base/components/email-signup/email-signup-header.twig
- sass/base/components/search/_search-block.scss
- sass/base/components/search/search.twig
> Tabbable ESU and Search close buttons

- sass/base/components/search/_search-block.scss
> Trigger new release

- sass/base/components/email-signup/_email-signup-head.scss
- sass/base/components/navigation/js/main-nav.js
- sass/themes/cr/2017/components/navigation/_main-nav.scss
> Minor nav fe issues fixes

- sass/base/components/news-article/_news-article.scss
> fix: remove news article padding on mobile

- sass/themes/sr/2018/components/navigation/_main-nav.scss
> Designed-requested tweaks

- sass/themes/cr/2017/components/navigation/_main-nav.scss
> CR nav 'donate' button targeting

- sass/themes/sr/2018/components/navigation/_main-nav.scss
> SR18 nav: nav position/layout fix for IE11 esu bug

- sass/base/components/teaser-block/_teaser-block.scss
> Teaser block fix for no image versions

- sass/themes/sr/2018/components/buttons/_buttons.scss
- sass/themes/sr/2018/components/buttons/buttons.twig
- sass/themes/sr/2018/sr18.scss
> SR18 button updates

- sass/themes/sr/2018/components/buttons/buttons.twig
- sass/themes/sr/2018/components/single-msg/_single-msg.scss
- sass/themes/sr/2018/sr18.scss
> Update single msg row for overflow

- sass/base/components/card-block/_card.scss
- sass/base/components/cards/cards.twig
fixes: #322 
- bg colour is set on the div with the .card class
> fix: card no-bg padding correction

- sass/themes/sr/2018/components/loading/_loading.scss
- sass/themes/sr/2018/sr18.scss
> feat: add animation blazy laoding

- sass/themes/sr/2018/components/background-colours/_background-colours.scss
- sass/themes/sr/2018/components/email-signup/_email-signup.scss
- sass/themes/sr/2018/sr18.scss
- sass/themes/sr/2018/variables/_mixins.scss
> BG Gradient mixin for ESU banners

- sass/themes/sr/2018/components/email-signup/_email-signup.scss
> Extend bg-gradient class for ESU, don't reuse mixin

- sass/themes/sr/2018/variables/_colours.scss
> fix: ruby colour

- sass/themes/sr/2018/components/links/_links.scss
- sass/themes/sr/2018/components/links/links.twig
- sass/themes/sr/2018/sr18.scss
- sass/themes/sr/2018/variables/_mixins.scss
- sass/themes/sr/2018/variables/_typography.scss
> feat: sr18 links

- sass/base/components/single-msg/_single-msg.scss
> fix: revert copy only

- sass/themes/sr/2018/components/lists/_lists.scss
- sass/themes/sr/2018/components/lists/lists.twig
- sass/themes/sr/2018/components/typography/_typography.scss
- sass/themes/sr/2018/sr18.scss
> feat: sr18 list colours

- sass/themes/sr/2018/components/navigation/_main-nav.scss
- sass/themes/sr/2018/components/search-results/_search-results.scss
- sass/themes/sr/2018/components/search/_search-block.scss
- sass/themes/sr/2018/components/search/search.twig
> feat: sr18 search dropdown styling

- sass/themes/sr/2018/components/background-colours/_background-colours.scss
- sass/themes/sr/2018/components/background-single-msg/_background-single-msg.scss
- sass/themes/sr/2018/components/single-msg/_single-msg.scss
- sass/themes/sr/2018/sr18.scss
> fix: sr18 single message background colour

- sass/themes/sr/2018/components/navigation/_main-nav.scss
- sass/themes/sr/2018/components/search-results/_search-results.scss
- sass/themes/sr/2018/components/search/_search-block.scss
> sr18 search dropdown bug

- sass/base/components/promo-header/_promo-header.scss
- sass/themes/sr/2018/components/promo-header/_promo-header.scss
Fixes https://github.com/comicrelief/pattern-lab/issues/398
> Header updates to keep text over promo image on all breakpoints

- sass/themes/sr/2018/components/promo-header/_promo-header.scss
> fix: SR18 video promo fix

- sass/base/components/promo-header/_promo-header.scss
> Fix: secondary/feat promo header fixes for IE11

- sass/base/components/promo-header/_promo-header.scss
- sass/themes/sr/2018/components/buttons/_buttons.scss
- sass/themes/sr/2018/components/email-signup/_email-signup-head.scss
- sass/themes/sr/2018/components/email-signup/_email-signup.scss
- sass/themes/sr/2018/components/search/_search-block.scss
- sass/themes/sr/2018/variables/_mixins.scss
> Fix: SR18 ESU button updates

- sass/themes/sr/2018/variables/_mixins.scss
> fix: adding focus state to btns

- sass/themes/donate/sr18/_donate-sr18-styles.scss
- sass/themes/donate/sr18/donate-page.twig
> 420: donate hide and show Apple Pay button

- sass/base/components/content-wall/content-wall.twig
- sass/base/components/teaser-block/teaser-block.twig
- sass/base/components/teaser-block/teaser-row.twig
- sass/themes/cr/2017/components/content-wall/content-wall.twig
- sass/themes/sr/2018/components/teaser-block/_teaser-block.scss
> Height fix for IE11, SR18 teaser block

- sass/themes/donate/sr18/_donate-sr18-styles.scss
- sass/themes/donate/sr18/components/promo-header/_promo-header.scss
- sass/themes/donate/sr18/donate-page.twig
- sass/themes/donate/sr18/donate-sr18.scss
> donate promo header styling

- sass/themes/donate/sr18/components/promo-header/_promo-header.scss
- sass/themes/donate/sr18/donate-page.twig
> 431: donate promo header id fix

- sass/themes/donate/sr18/components/form/_form.scss
- sass/themes/donate/sr18/donate-page.twig
> fix: donate postcode search button

- sass/themes/donate/sr18/_donate-sr18-styles.scss
- sass/themes/donate/sr18/components/form/_form.scss
fixes: #459 
- background colour on body to fix white bg colour when page is short
- iOS fix for search button styling
> 459: donate styling fixes

- sass/themes/donate/sr18/components/form/_form.scss
> donate selectbox  fix for Windows

- sass/base/components/navigation/_footer-nav.scss
Added hover and focus state to footer links
> SR18 Added hover state to footer links

- sass/base/core/_base-1-mixins.scss
- sass/themes/sr/2018/components/app-link-block/_app-link-block.scss
- sass/themes/sr/2018/components/app-link-block/app-link-block.twig
- sass/themes/sr/2018/components/app-link-block/images/success-tick.svg
- sass/themes/sr/2018/sr18.scss
- sass/themes/sr/2018/variables/_colours.scss
- sass/themes/sr/2018/variables/_mixins.scss
- Added new styles and template for
> sr18 app link styles

- sass/themes/sr/2018/components/app-link-block/_app-link-block.scss
> Reposition ajax loader for app link block

- sass/themes/sr/2018/components/news-article/_news-article.scss
- sass/themes/sr/2018/components/news-article/news-article.twig
- sass/themes/sr/2018/variables/_colours.scss
- updated styles for news article caption
> sr18 update news article caption styles

- sass/themes/sr/2018/components/footer-app-links-block/_footer-app-links-block.scss
> Footer App Link block position fix

- sass/themes/payin/sportrelief/components/failure/_failure.scss
- sass/themes/payin/sportrelief/pages/failure-page.twig
- sass/themes/payin/sportrelief/payin-sportrelief.scss
fixes:#456
Added new styles and updated the template
> Payin - failure page

- sass/themes/payin/default/components/_payin-form.scss
- sass/themes/payin/sportrelief/components/form/_form.scss
- sass/themes/payin/sportrelief/components/success/_success.scss
- sass/themes/payin/sportrelief/pages/payin-page.twig
- sass/themes/payin/sportrelief/pages/success-page.twig
> fix: payin checkboxes

- sass/base/components/navigation/js/main-nav.js
> Update JS to switch aria attr on focus events

- sass/themes/sr/2018/components/live-total-block/live-total-block.twig
removed unnecessary attributes
> Fixing missing feature release

- sass/themes/donate/donate-cr/components/form/_form.scss
> feat: donate - cr donate theme main form width

- sass/themes/sr/2018/components/buttons/_buttons.scss
- sass/themes/sr/2018/components/buttons/buttons.twig
- sass/themes/sr/2018/components/typography/_typography.scss
- sass/themes/sr/2018/components/typography/typography.twig
- sass/themes/sr/2018/variables/_typography.scss
> SR18 OTN btn and h1 variants

- sass/themes/donate/donate-cr/components/partner-footer/_partner-footer.scss
- sass/themes/donate/donate-cr/donate-cr.scss
- sass/themes/donate/donate-cr/variables/_colours.scss
- sass/themes/donate/donate.scss
- sass/themes/donate/sr18/donate-page.twig
Added new partner styles
Updated markup of partner footer
> Add donate cr theme partner footer

- sass/themes/sr/2018/components/buttons/_buttons.scss
> OTN alt btn update

- sass/themes/donate/donate-cr/components/form/_form.scss
> fix: donate cr sub theme checkbox styling

- README.md
- sass/themes/sr/2018/components/cookie-consent/_cookie-consent.scss
- sass/themes/sr/2018/components/cookie-consent/cookie-consent.json
- sass/themes/sr/2018/components/cookie-consent/cookie-consent.twig
- sass/themes/sr/2018/sr18.scss
> SR18 cookie banner style tweaks

- Gruntfile.js
- sass/themes/donate/donate-cr/components/form/_form.scss
- sass/themes/donate/donate-cr/components/promo-header/_promo-header.scss
- sass/themes/donate/donate-cr/donate-cr.scss
- sass/themes/donate/donate-cr/variables/_colours.scss
- sass/themes/payin/default/components/_payin-form.scss
- sass/themes/payin/default/components/images/drop-down-dark-purple.svg
fixes: #543
form style tweaks:
- dark purple colour for form elements
- dark purple arrow for select box
- styling for keep in touch row and bfpo text
> donate cr-donate more form styling

- sass/themes/sr/2018/components/live-total-block/_live-total-block.scss
- fixed centring of step totaliser
> Center step counter totaliser

- sass/themes/donate/donate-cr/components/promo-header/_promo-header.scss
- sass/themes/donate/sr18/failure-page.twig
update the promo header to remove background image for failure pages
> donate cr theme failure page 

- sass/themes/donate/donate-cr/components/success/_success.scss
fixed misalignment of cta button
> Donate CR Theme - failure page center button alignment

- sass/themes/payin/default/components/_payin-form.scss
- sass/themes/payin/sportrelief/components/success/_success.scss
- sass/themes/payin/sportrelief/pages/success-page.twig
Added new help info class for for additional copy change
> Thank you copy change

- sass/themes/donate/donate-cr/components/form/_form.scss
- sass/themes/donate/sr18/components/form/_form.scss
- sass/themes/donate/sr18/donate-page.twig
fixes: #555 
preview environment: https://donate-preview.cfapps.io/?site=CRDONATE
> donate error messages

- sass/themes/payin/default/components/_payin-form.scss
- sass/themes/payin/sportrelief/components/cards/_cards.scss
- sass/themes/payin/sportrelief/components/form/_form.scss
- sass/themes/payin/sportrelief/components/promo-header/_promo-header.scss
- sass/themes/payin/sportrelief/components/success/_success.scss
- sass/themes/payin/sportrelief/pages/payin-page.twig
- sass/themes/payin/sportrelief/payin-sportrelief.scss
> Payin - design review changes

- sass/themes/cr/2017/components/navigation/_main-nav.scss
> Header adjustment to accommodate nav fully

- sass/themes/donate/donate-cr/components/form/_form.scss
- sass/themes/donate/donate-cr/components/header/_header.scss
- sass/themes/donate/sr18/components/form/_form.scss
fixes: #572 
Can be previewed here: https://donate-preview.cfapps.io/?site=CRDONATE
> donate cr subtheme design review

- .snyk
- yarn.lock
https://snyk.io/vuln/npm:sshpk:20180409
> fix: Update libs, primarily to fix sshpk security vulnerability

- sass/base/_components.scss
- sass/base/components/just-in-time-block/_just-in-time.scss
- sass/base/components/just-in-time-block/just-in-time-block.twig
- sass/themes/cr/2017/components/navigation/_main-nav.scss
- sass/themes/donate/donate-cr/donate-cr.scss
- sass/themes/donate/sr18/donate-page.twig
> Added new component just in time message

- sass/themes/donate/donate-cr/components/form/_form.scss
#576 
fix: made generic form section class for show and hide easier to update layout
> Made generic form section class name for show and hide

- sass/themes/donate/donate-cr/components/form/_form.scss
- yarn.lock
> fix: cr-donate giftaid copy

- sass/base/components/just-in-time-block/_just-in-time.scss
> fix: update JIT msg block selector

- sass/base/components/footer/_footer.scss
- sass/themes/donate/sr18/donate-page.twig
fixes: https://github.com/comicrelief/pattern-lab/issues/571
> Footer CR Logo spacing between content

- sass/themes/rnd/2017/components/_theme.scss
> Fix RND nav after campaign update

- sass/base/components/just-in-time-block/_just-in-time.scss
- sass/themes/cr/2017/cr17.scss
> Add JIT block to CR theme, remove heavy-handed font override

- sass/themes/frost/sr18/components/_just-in-time.scss
- sass/themes/frost/sr18/sr18.scss
> SR18 overrides for FROST jit block

- sass/themes/shop/2018/_shop18-components.scss
- sass/themes/shop/2018/shop18.scss
- sass/themes/sr/2018/components/just-in-time-block/_just-in-time-block.scss
- sass/themes/sr/2018/components/just-in-time-block/just-in-time-block.twig
- sass/themes/sr/2018/sr18.scss
> Adding JIT block to shop theme with SR18 overrides

- sass/themes/sr/2018/components/navigation/_main-nav.scss
> Update nav to use generic logo from Drupal only

- sass/themes/sr/2018/components/navigation/_main-nav.scss
> Nav fix: tweak lg breakpoint logo on scroll

- sass/themes/frost/core/components/_form.scss
- sass/themes/frost/core/components/form--frost.twig
- sass/themes/frost/frost.scss
Related to https://comicrelief.atlassian.net/browse/GP-999
> Accessibility improvements for registration journey

- sass/base/core/_base-reset.scss
Required by https://comicrelief.atlassian.net/browse/GP-1475
> Set a width on legend element

- sass/base/components/form/_standard-form.scss
- sass/base/components/form/form.twig
added missing checkbox classname
> Add missing checkbox classname

- README.md
Updates CI paths for build logo, etc...
> Update CI paths

- sass/themes/donate/donate-cr/components/cards/_cards.scss
add styles to card donate styles to allow background images
> Extend cards on success to allow background images

- sass/themes/cr/2017/components/links/_links.scss
- sass/themes/cr/2017/components/links/links.twig
feat: extend CR theme link styles
> Add new link styles for CR theme

- sass/base/components/just-in-time-block/_just-in-time.scss
Added new just in time show content class to work with react component in storybook
> Add just in time show content class

- sass/themes/cr/2017/components/buttons/_buttons.scss
> Add text shadow to CR Theme button for visually impaired users

- sass/themes/frost/core/components/_campaign-images.scss
> fix: add focus state to GP reg campaign selection btns

- sass/themes/cr/2017/components/buttons/_buttons.scss
- sass/themes/donate/donate-cr/components/form/_form.scss
- sass/themes/donate/donate-cr/donate-cr.scss
> Donate Theme CR -  fix error message

- sass/themes/sr/2018/components/search/_search-block.scss
fix search box and button alignment
> SR - Fixed alignment of search box and close button

- sass/base/components/postcode-lookup/_postcode-lookup.scss
- sass/base/components/postcode-lookup/postcode-lookup.twig
- sass/base/core/_base-1-mixins.scss
preview: https://deploy-preview-47--giftaid-react.netlify.com/
> fix: clearfix for postcode lookup

- sass/themes/cr/2017/components/just-in-time-block/_just-in-time-block.scss
- sass/themes/donate/donate-cr/donate-base-cr.scss
feat: created new donation base theme
> Create new donation theme

- sass/themes/frost/frost.scss
> fix: attempt to trigger semver after updating npm token

- sass/base/components/promo-header/_promo-header.scss
fixes: #691 
preview here: http://pr-536-rrjcqoa-3g6y4v7pqt6nk.eu.platform.sh/
> fix: min height for promo header with video background

- sass/base/components/just-in-time-block/_just-in-time.scss
fix: https://github.com/comicrelief/react-donation/issues/91
> Hide just in time content to screen reader when closed

- sass/themes/donate/donate-cr/components/giving-type-selector/_giving-type-selector.scss
- sass/themes/donate/donate-cr/donate-base-cr.scss
fixes: #721 
preview environment here: https://deploy-preview-175--comicrelief-donation.netlify.com/
> donate giving type selector styling

- sass/themes/donate/donate-cr/components/giving-type-selector/_giving-type-selector.scss
preview here: https://deploy-preview-175--comicrelief-donation.netlify.com/?clientOverride=test-recurring
> fix: cr donate font weight fix for giving type selector

- sass/themes/donate/donate-cr/components/money-buy-block/_money-buy-block.scss
preview here: https://deploy-preview-192--comicrelief-donation.netlify.com/?clientOverride=test-recurring
> donate money buy buttons gap fix

- sass/themes/cr/2017/components/navigation/_expanded-footer.scss
> fix: turbofooter style tweaks

- sass/base/components/email-signup/_email-signup-head.scss
> fix: CR ESU bug fix

- .snyk
- package.json
- yarn.lock
Fix synk issues with suggestion solutions
> Upgrade underscore.string and add revert event-stream @3.3.4

- yarn.lock
> fix: post GH issue re-release

- sass/themes/cr/2019/_cr19-components.scss
> Cr19 nav height fix

- sass/themes/cr/2019/components/buttons/_buttons.scss
- sass/themes/cr/2019/components/fixed-ratio-image/_fixed-ratio-image.scss
- sass/themes/cr/2019/components/full-height-double-image-single-copy/_full-height-double-image-single-copy.scss
- sass/themes/cr/2019/components/full-height-single-image-single-copy/_full-height-single-image-single-copy.scss
- sass/themes/cr/2019/components/full-height-single-image-triple-copy/_full-height-single-image-triple-copy.scss
- sass/themes/cr/2019/components/typography/_typography.scss
> CR19 theme: font and component tweaks

- sass/themes/cr/2019/components/full-height-double-image-single-copy/_full-height-double-image-single-copy.scss
- sass/themes/cr/2019/components/typography/_typography.scss
- sass/themes/cr/2019/variables/_typography.scss
> Fontsize and linebreak fixes

- sass/kss/cr19.scss
- sass/themes/cr/2019/_cr19-styleguide.scss
- sass/themes/cr/2019/components/typography/_typography.scss
- sass/themes/cr/2019/form.twig
- sass/themes/shop/2019/_shop19-components.scss
- sass/themes/shop/2019/_shop19-styleguide.scss
- sass/themes/shop/2019/form.twig
- sass/themes/shop/2019/shop19.scss
- yarn.lock
> Updates for Shop theme

- sass/themes/cr/2019/components/just-in-time-block/_just-in-time-block.scss
- sass/themes/shop/2019/_shop19-components.scss
> JIT and font updates for Shop

- sass/themes/cr/2019/variables/_typography.scss
> Update font sizes

- sass/themes/cr/2019/components/background-colours/_background-colours.scss
> fix: bg font colour rules

- sass/themes/cr/2019/variables/_typography.scss
> fix: set-up fallback fonts CR19

- sass/themes/cr/2019/components/navigation/_main-nav.scss
- sass/themes/cr/2019/components/navigation/main-nav.twig
> Fix dropdown bug

- sass/themes/cr/2019/components/full-height-double-image-single-copy/_full-height-double-image-single-copy.scss
- sass/themes/cr/2019/components/full-height-double-image-single-copy/full-height-double-image-single-copy.twig
- sass/themes/cr/2019/components/full-height-single-image-triple-copy/_full-height-single-image-triple-copy.scss
- sass/themes/cr/2019/components/full-height-single-image-triple-copy/full-height-single-image-triple-copy.twig
> Make VH-based component heights more flexible

- sass/base/components/form/_standard-form.scss
- sass/base/components/form/form.twig
> marketing consent horizontally inline checkboxes

- sass/themes/cr/2019/cr19.scss
> fix: Retry build

- sass/themes/cr/2019/components/cookie-consent/_cookie-consent.scss
- sass/themes/cr/2019/components/cookie-consent/cookie-consent.twig
> Cookie banner tweaks

- sass/themes/cr/2019/components/single-msg/_single-msg.scss
> Update single msg row padding

- package.json
- sass/base/components/lightcase/_lightcase.scss
- yarn.lock
> Lightbox SM breakpoint fix

- sass/base/components/cards/_cards.scss
- sass/themes/base/base-styleguide.scss
- sass/themes/cr/2019/_cr19-styleguide.scss
- yarn.lock
> Updates required for Membership page on CR.com

- sass/themes/cr/2019/components/navigation/_main-nav.scss
preview here: http://pr-721-pu4yoqa-3g6y4v7pqt6nk.eu.platform.sh/
> cr19 main nav spacing decrease to fit in another link

- sass/base/components/lightcase/_lightcase.scss
> fix: Fullwidth container for lightcase

- package.json
- yarn.lock
> Attempt to fix Customizr dep

- sass/themes/cr/2019/components/typography/_typography.scss
> Tweak layout classes and available font colours for Membership

- sass/themes/cr/2019/components/membership-signup/js/membership-signup.js
> Fix siteurl params for Membership row

- sass/themes/cr/2019/variables/_colours.scss
> fix: revert bg-grey back to proper value

- sass/themes/cr/2019/components/membership-signup/js/membership-signup.js
- sass/themes/cr/2019/components/membership-signup/membership-signup.twig
> Membership: add params rowID to redirect link

- sass/themes/cr/2019/components/membership-signup/js/membership-signup.js
> Refactor js for membership datalayer

- sass/themes/cr/2019/components/membership-signup/js/membership-signup.js
> Fix cookie 'remove' logic

- sass/themes/cr/2019/components/membership-signup/_membership-signup.scss
> Accessbility and layout tweaks for mship row

- sass/themes/donate/components/partner-footer/_partner-footer.scss
> Update donate partner design style 

- sass/themes/sr/2018/components/bg-graphics/_bg-graphics.scss
- sass/themes/sr/2018/components/full-height-single-image-single-copy/_full-height-single-image-single-copy.scss
- sass/themes/sr/2018/sr18.scss
> SR20 theme bg graphics

- sass/base/core/_base-1-mixins.scss
- sass/themes/donate/components/background-colours/_background-colours.scss
- sass/themes/donate/components/buttons/_buttons.scss
- sass/themes/donate/components/form/_form.scss
- sass/themes/donate/components/full-height-single-image-single-copy/_full-height-single-image-single-copy.scss
- sass/themes/donate/components/giving-type-selector/_giving-type-selector.scss
- sass/themes/donate/components/money-buy-block/_money-buy-block.scss
- sass/themes/donate/components/partner-footer/_partner-footer.scss
- sass/themes/donate/components/success/_success.scss
- sass/themes/donate/components/typography/_typography.scss
- sass/themes/donate/variables/_colours.scss
- sass/themes/donate/variables/_mixins.scss
- sass/themes/donate/variables/_typography.scss
> Donate theme updates

- sass/themes/donate/components/money-buy-block/_money-buy-block.scss
> Semvar kickstart

- sass/themes/sr/2018/components/copy-video/js/copy-video.js
> Update YT API usage
